/* Player guidance shared by the Mini App and the pre-rendered website pages.
 * After editing, run node scripts/sync-moonpet-guide.mjs.
 * Numeric contracts are checked against the Worker by moonpet-guide.test.mjs.
 */
(function (root, factory) {
  var guide = factory();
  if (typeof module === 'object' && module.exports) module.exports = guide;
  else root.MoonpetGuide = guide;
})(typeof window === 'object' ? window : globalThis, function () {
  'use strict';
  var stages = [
    { stage: 1, name: 'Street Moonpet', level: 5, days: 7, marks: 7, crests: 1, bosses: 0, relics: 0, scrap: 5, fragments: 0 },
    { stage: 2, name: 'Cyber Moonpet', level: 20, days: 28, marks: 21, crests: 3, bosses: 3, relics: 2, scrap: 10, fragments: 3 },
    { stage: 3, name: 'Elite Moonpet', level: 35, days: 84, marks: 60, crests: 10, bosses: 8, relics: 5, scrap: 20, fragments: 8 },
    { stage: 4, name: 'Moon Guardian', level: 45, days: 182, marks: 120, crests: 22, bosses: 12, relics: 8, scrap: 36, fragments: 20 },
    { stage: 5, name: 'Legendary Moon Guardian', level: 50, days: 365, marks: 240, crests: 44, bosses: 15, relics: 10, scrap: 60, fragments: 40 }
  ];
  var care = [
    { key: 'feed', name: 'Feed', energy: 4, hunger: -28, happiness: 2, cleanliness: -2, pet_xp: 6, community_xp: 2, gold: 5, crystals: 0, style_tokens: 0 },
    { key: 'play', name: 'Play', energy: -12, hunger: 8, happiness: 22, cleanliness: -6, pet_xp: 10, community_xp: 3, gold: 7, crystals: 0, style_tokens: 1 },
    { key: 'clean', name: 'Clean', energy: -3, hunger: 2, happiness: 4, cleanliness: 32, pet_xp: 6, community_xp: 2, gold: 4, crystals: 0, style_tokens: 0 },
    { key: 'sleep', name: 'Sleep', energy: 36, hunger: 10, happiness: 1, cleanliness: -2, pet_xp: 5, community_xp: 1, gold: 3, crystals: 0, style_tokens: 0 },
    { key: 'train', name: 'Train', energy: -18, hunger: 12, happiness: 8, cleanliness: -4, pet_xp: 20, community_xp: 6, gold: 10, crystals: 1, style_tokens: 0 }
  ];
  function signed(value) { return (value > 0 ? '+' : '') + value; }
  var stageList = '<ul>' + stages.map(function (s) {
    return '<li><b>Stage ' + s.stage + ': ' + s.name + '</b> — level ' + s.level + ', at least ' + s.days + ' days owned, ' + s.marks + ' Growth Marks and ' + s.crests + ' Weekly Crest' + (s.crests === 1 ? '' : 's') + '; ' +
      (s.bosses ? s.bosses + ' Alley King victories, ' + s.relics + ' owned relics; ' : '') +
      'spend ' + s.scrap + ' Scrap Metal' + (s.fragments ? ' and ' + s.fragments + ' Evolution Fragments' : '') + '.</li>';
  }).join('') + '</ul>';
  var careList = '<ul>' + care.map(function (c) {
    return '<li><b>' + c.name + '</b> — energy ' + signed(c.energy) + ', hunger ' + signed(c.hunger) + ', happiness ' + signed(c.happiness) + ', cleanliness ' + signed(c.cleanliness) + '. Base reward: ' + c.pet_xp + ' Pet XP, ' + c.community_xp + ' Community XP, ' + c.gold + ' Moon Gold' + (c.crystals ? ', 1 Moon Crystal' : '') + (c.style_tokens ? ', 1 Style Token' : '') + '.</li>';
  }).join('') + '</ul>';
  var sections = [
    { id: 'start', title: 'Qualify And Adopt', body: '<p>Earn <b>1,000 lifetime Arcade XP</b> in the website Arcade using the same linked Telegram account. Community XP, Pet XP and your spendable Arcade balance are different scores. The first pet is free: qualifying keeps your Arcade XP. Existing pet owners keep access.</p><p>Open @WIKICOMSBOT and launch Moonpet OS. Telegram signs your session. On HOME, choose <b>Activate EGGYONE</b> to adopt the Secret Bot. If entry is locked, follow the Arcade link and earn the remaining XP shown, then refresh.</p>' },
    { id: 'incubation', title: 'Incubate, Hatch And Breakout', body: '<p>In HOME’s Secret Bot Chamber, choose <b>Warm Bot, Talk to Bot, Inspire Bot or Let It Rest</b>. Each accepted action adds 2 signal, up to 12; at most 8 incubation actions count per pet per UTC day. Use at least three different types. These actions cost no currency or energy and have no timed cooldown. Accepted incubation care can earn one Growth Mark for that pet’s day, including after signal reaches 12.</p><p><b>HATCH BOT</b> becomes available after at least 7 full days of incubation with 12 signal and three care types, or after 14 full days even without those signals. Read the live age and readiness in HOME; filling the meter alone does not shorten the wait. At 14 days hatching is available, but you still press HATCH BOT.</p><p>Hatching saves the young companion and opens the hatched gameplay routes. <b>BREAKOUT</b> is the EGGYONE hatch animation, followed by the shared WTFBOI presentation. It is not the canonical identity reveal. The identity remains <b>UNKNOWN</b> through Stages 0, 1 and 2, and becomes visible only at <b>Stage 3, Elite Moonpet</b>.</p><p>Hatching and formal evolution are separate: the client can show WTFBOI after hatching while PROFILE still lists Stage 0 until you meet and confirm the Stage 1 evolution requirements.</p>' },
    { id: 'navigation', title: 'Current Build In Moonpet OS', body: '<p><b>HOME</b>: needs, care, Daily Cache and Play Now. <b>MISSIONS</b>: seven daily missions, Daily Journey, Weekly Journey, achievements, Continuing Contracts and Season Finale. <b>EXPLORE</b>: runs, districts, adventures, street events, stories, bosses, Arena and Kaiju. <b>WORK</b>: jobs and timed activities. <b>ECONOMY</b>: gear, materials, crafting, bounties, expeditions, Market and bag. <b>PROFILE</b>: pet spaces, evolution, identity, memories, alerts, season rewards, ranks, How to Play and About.</p><p>Open a panel to compare its requirement, cost, timer and reward before tapping an action. HOME’s Coach and <b>Play Now</b> link to useful available routes; opening a route spends nothing. Pet, Care, Daily Journey, Weekly Journey, Jobs, Runs, Equipment, Arena, Kaiju and Progression are the current gameplay priorities.</p>' },
    { id: 'evolution', title: 'Pet Stages And Realistic Timing', body: '<p>Stage 0 is Secret Bot / EGGYONE. Pet XP raises your level; it does not automatically evolve your pet. In PROFILE, read the next gate and choose <b>Evolve</b> when all requirements are met. Stages must be completed in order.</p>' + stageList + '<p>Age, Marks, Crests, boss victories and relic counts belong to that pet. Materials are consumed at each evolution; the other requirements are thresholds, not payments. Marks count distinct days and Crests count distinct pet Journey weeks. Later stages unlock jobs and events and improve weekly boss damage.</p><p>These are minimum ages, not promised completion dates: plan for at least four weeks to Cyber, twelve weeks to the identity reveal, about six months to Guardian and a year to Legendary. Missing objectives, boss wins or materials can take longer. Legendary completion also requires final evolution, 240 distinct-day Marks and 44 distinct-week Crests. The first evolution also needs a Weekly Crest, including two qualifying Daily Cache check-in days in the same pet Journey week; hatching alone does not supply it. There is no competition-season deadline for this lifetime Journey.</p>' },
    { id: 'pets', title: 'Pet Spaces, Switching And Deletion', body: '<p>New purchases allow <b>three owned pet spaces across all seasons</b>: Pet 1 is free after qualification; Pet 2 costs <b>500 spendable Arcade XP</b>; Pet 3 costs <b>1,000 spendable Arcade XP</b>. Buy them in order in PROFILE. Existing historical rosters are retained, including rosters above the new-purchase limit.</p><p>One pet is selected at a time. In PROFILE, select an owned pet to continue its needs, identity, XP, specialist tracks, Marks, Crests, memories and loadout. Currencies, inventory and owned gear are shared by the account; equipped choices belong to each pet. Switching does not refresh account cooldowns, daily attempts or caps. Finish, claim or cancel pending activities, runs and battles when the switch control asks you to.</p><p><b>Pets persist: no automatic seasonal reset, replacement or retirement.</b> To start over voluntarily, choose Delete for a pet in PROFILE and confirm that pet. Settle saved rewards and finish or cancel blocking sessions first. Deletion archives that companion permanently and creates a fresh egg in the same owned space without another Arcade XP charge. The new pet starts its own age and progression. Purchased spaces, account currencies, items and reward history remain; deleting cannot refund XP, replay paid rewards or resume the old pet.</p>' },
    { id: 'care', title: 'Care Actions, Costs And Benefits', body: '<p>After hatching, use HOME’s Care panel. Lower hunger is better; higher energy, happiness and cleanliness are better. Needs change while you are away, so check them before a risky route. Each of Feed, Play, Clean, Sleep and Train has a <b>45-second account cooldown for that action</b>. There is no currency fee for these buttons.</p>' + careList + '<p>Train requires at least <b>18 energy</b>. Sleep and Train are blocked while a background activity runs; Feed, Play and Clean remain available. Sleep in Care is instant, separate from timed Sleep in WORK. Gear can improve normal care benefits; stat limits, wallet limits and daily XP caps still apply. Care builds Care/Bond progress; training builds Training progress and eligible equipped gear can gain mastery.</p><p><b>Energy Drink</b> in Care restores up to 28 energy: 10-minute cooldown, 3 uses per account per UTC day. <b>Dance</b> adds up to 18 happiness: 5-minute cooldown, 5 daily uses. <b>Cuddles</b> adds up to 8 happiness: 5-minute cooldown, 5 daily uses. These three work for eggs too, cost no currency or bag item and award no XP, currency, specialist progress or incubation signal. The bag’s Energy Drink is a separate consumable: it consumes one item for up to 22 energy and 6 Pet XP.</p>' },
    { id: 'missions', title: 'Seven Daily Missions And Claims', body: '<p>In MISSIONS, complete Feed; Train once; Feed + Play + Clean; one Moon Gold trade; buy new permanent gear or upgrade owned gear; one adventure; and bank 50 Moon Gold. Districts, stories, raids and completed/extracted Moon Runs can also qualify for the adventure goal. Free gear switching, Market purchases and crafting do not qualify for shopping; a fully upgraded permanent gear collection completes that goal automatically.</p><p>Check off all seven, then press <b>Claim 7/7 Bonus</b> for up to 25 Pet XP, 50 Moon Gold and 1 Style Token, once per account per UTC day. Reaching 50 Gold stays recorded even if you spend it. Complete unclaimed days survive midnight. XP goes to the selected hatched pet when the claim starts; retries keep that original pet. Mission ticks are saved progress, not a separate payout for every tick. Claim unlocked achievements and completed bounties using their own buttons.</p><p><b>Daily Cache</b> is HOME’s account daily claim and counts as a check-in. Claim it once per UTC day; its panel shows the actual capped payout. This is separate from the 7/7 bonus and Journey awards.</p>' },
    { id: 'daily', title: 'Daily Journey And Growth Marks', body: '<p>After hatching, MISSIONS shows five official objectives: defeat 3 Daily Run enemies; reach Daily Run depth 7; successfully extract from the official Daily Run; defeat its Alley King boss; and complete 3 accepted Feed, Play, Clean or Sleep actions. Complete <b>any 3 of these 5</b> to earn a Growth Mark automatically. Only the official Daily Run supplies its run objectives; Contracts and Standard runs do not.</p><p>The cap is one Growth Mark per pet per UTC day, shared with incubation’s daily Mark. Completing more objectives cannot add a second Mark that day. Watch the server-recorded progress and awarded status; use the saved recovery option if delivery was interrupted.</p>' },
    { id: 'weekly', title: 'Weekly Journey And Crests', body: '<p>Complete <b>all five</b> objectives on the same pet: 5 accepted Feed/Play/Clean/Sleep actions, 3 Train actions, 3 completed or extracted qualifying runs, 1 Weekly Boss attempt and 2 Daily Cache check-ins. Standard Moon Run completion/extraction and official Daily Run finishes count toward runs; Contracts do not. A Weekly Crest is awarded automatically once the full set is proven.</p><p>One Crest per pet per Journey week. New pets use seven-day windows starting on their adoption UTC date, rather than the leaderboard’s Monday reset. Older pets can retain a legacy Journey clock with a different boundary. Check the panel’s exact reset time. Switching pets cannot transfer objectives.</p>' },
    { id: 'work', title: 'Jobs And Timed Activities', body: '<p>In WORK, choose among 14 jobs. Cards show level, evolution and any specialist requirement plus base rewards. Instant jobs have no pet energy debit and share a <b>45-second account job cooldown</b>. Jobs earn Pet XP, currencies and Job progression.</p><p>For background activity, choose <b>Sleep, Train, Work or Explore</b>. One account activity runs at a time. It continues while the app is closed or you play Contracts. Minimum claim time: <b>5 minutes</b>. Training caps at <b>2 hours</b>; Sleep, Work and Explore cap at <b>8 hours</b>. Claim ends the session and applies the displayed elapsed-time rewards and stat costs; Cancel ends it with no reward. Sleep restores needs; Train, Work and Explore advance their matching specialist tracks.</p><p>Compare the current claim preview and next checkpoint: energy costs change with elapsed time, rather than being a flat entry charge. Explore pays one crystal from 30 minutes to below 2 hours; at 2 hours an Adventure Map replaces it. Waiting past the cap adds no rewards. An unclaimed active session expires <b>24 hours after its cap</b>; a saved interrupted reward has its own recovery state.</p>' },
    { id: 'explore', title: 'Exploration, Stories And Raids', body: '<p>In EXPLORE, Adventure routes require at least <b>18, 26 or 34 energy</b> for their respective entry gates and share a <b>30-minute account cooldown</b>. That energy gate is separate from the actual outcome’s displayed energy cost. Compare each approach’s odds, normal reward and setback before choosing. Street Events also show their costs and risk; the first 6 rewarded events per account per UTC day use full rewards, the next 4 use half, and later events award no progression rewards.</p><p>District missions cost <b>10 energy</b> and show their level gate and approach risk; each district has one rewarded mission per account per UTC day. Stories allow one rewarded step per chain per UTC day. Saved decisions preserve the original choice and outcome.</p><p><b>Seasonal Raid</b>: one attack per pet per UTC day after its displayed level gate. Conserve Energy costs 12 energy for lower damage; Steady Strike and the boss-specific counter cost 18. Counter cards show success and setback damage; they affect that hit, not an ongoing Arena status. Damage persists through the rotation. Claim saved defeated-boss rewards without another attack.</p>' },
    { id: 'runs', title: 'Standard Moon Run And Official Daily Run', body: '<p><b>Standard Moon Run</b> in EXPLORE has 100 rooms. Read the room’s opponent, objective, chance, costs and gear effects; energy must be above zero to take a room step and the chosen outcome applies its own displayed costs. Loot stays unbanked until extraction or completion. Choose Extract to secure the bag and Adventure progress; failure loses the bag but may keep a small XP lesson. Elite encounters occur every five rooms and district bosses every ten. A Lucky Charm (<code>lucky_charm</code>) can be consumed when it boosts a run.</p><p><b>Official Daily Moon Run</b> is one attempt per account per UTC day. It uses route health and score, with no pet energy debit and no Standard unbanked XP bag. Its seeded rooms supply Daily Journey evidence. Safe choices improve odds at lower score; bold choices risk more for score. After rooms 3 and 6, choose Guardian, Striker or Scavenger or skip the upgrade. Reach the last room and defeat Alley King to finish; early extraction consumes the attempt. Finish Saved Daily Run repairs an interrupted ending without using another attempt.</p>' },
    { id: 'contracts', title: 'Continuing Contracts', body: '<p>After hatching, open MISSIONS or Play Now. Choose a quest, Scout/Bruiser/Scavenger build, difficulty and route length, then press the quest button. Standard routes have 6 rooms and 2 upgrade drafts; Long routes have 10 rooms and 4 drafts. Higher difficulties unlock after 5 and 15 successful contracts. Selecting a route record fills the controls; it does not start a quest.</p><p>Clear the final boss tactic and meet the main goal to earn Contract Rank. Scouts, patches, checkpoint paths, field decisions and owned relics modify route odds and resources; compare the live costs before committing. They use the contract’s supplies, health and salvage, not pet energy or account currency. Failed or abandoned contracts earn no clear.</p><p>Contracts are saved online, with no pet energy cost or cooldown. Start another immediately after finishing. The first three successes per account per UTC day offer up to 20 Pet XP each, within the normal cap; later play still builds Contract Rank and route records. Rank and collection records add no currency, items, Growth Marks, Weekly Crests or official Daily Run credit.</p>' },
    { id: 'combat', title: 'Arena And Kaiju', body: '<p><b>Pet Arena</b> requires a hatched active Moonpet at level 10. Choose solo CRT or player matchmaking in EXPLORE. Attack Head is stronger but less accurate and is countered by Block Head; Attack Body is more reliable and countered by Block Body. Attack attempts build charge, Charge Special guarantees one charge, and Special Move needs three. Solo CRT shows its next intent; player intent stays hidden until both lock. Level, condition and Battle Loadout affect resolution. Arena has no pet energy entry or result debit; low energy can still weaken battle power.</p><p><b>Kaiju Sticker Battle</b> requires a hatched active Moonpet. Choose solo CRT or matchmaking, then a card. The server picks Power, Size, Attack, Defence, Speed or Legacy before cards lock. Compare the displayed category values; the higher value wins and equal values draw. Rival cards remain hidden until resolution.</p><p>Kaiju result settlement charges <b>6 energy for a win, 5 for a draw or 4 for a loss</b>, once from the participating pet. Insufficient energy holds the payout for recovery; restore that pet’s energy and retry the saved result. Account reward slots give full rewards for the first 5 results each UTC day, half for the next 5, then no progression rewards. Energy still applies to later results. Switching or retrying cannot change the original participant or charge twice.</p>' },
    { id: 'bosses', title: 'Weekly Boss And Season Finale', body: '<p><b>Weekly Boss</b> requires a hatched level-5 pet. Strike, Outsmart and Endure each cost <b>12 energy</b>; inspect the damage preview and weakness bonus. Endure deals damage rather than healing. All pets share one account attack per UTC day; accumulated damage resets Monday at 00:00 UTC. Recover Weekly Reward collects a saved victory without another attack.</p><p>After the shared boss is defeated, a pet missing the attempt for its own Journey week can take a <b>participation challenge</b> once that week for 12 energy. It records that pet’s attempt only: no extra damage, XP, currency or boss-win credit. It does not finish the other Crest objectives.</p><p><b>Season Finale: Signal Sovereign</b> in MISSIONS needs final evolution, 240 distinct-day Marks and 44 distinct-week Crests; already completed pets also qualify. Pick Striker, Guardian or Tactician, read the next attack, Guard to build charge and Surge when the core is exposed. Repair kits restore battle health. This saved-turn fight uses separate battle supplies and health with no pet energy cost; defeat allows an immediate free retry. Claim Finale Reward pays up to 100 Pet XP, 200 Moon Gold and 5 Style Tokens once per pet per competition quarter. Previous-quarter fights and rewards remain recoverable.</p>' },
    { id: 'economy', title: 'Equipment, Currency And Rewards', body: '<p><b>Pet XP</b> raises the earning pet’s level. <b>Moon Gold</b>, <b>Moon Crystals</b> (labelled Gems in some controls) and <b>Style Tokens</b> are shared game currencies for game-only rewards, gear, upgrades, bundles and cosmetics, with no cash-out path. Energy is a need, not currency.</p><p>In ECONOMY, compare level gates, exact price and benefit, then Buy, Upgrade or Equip. Care Loadout uses <b>Food, Toy and Outfit</b>; Battle Loadout uses <b>Armor, Weapon and Charm</b>. Changing one does not reset the other. Empty battle slots display <b>none</b>. Equipping owned gear is free; upgrades spend the displayed currencies/materials. Gear affects gameplay; it is not painted as clothing on animation frames. Style Lab cosmetics and Rare Morph backgrounds change presentation.</p><p>Claim four rotating daily <b>Bounties</b> after their accepted-action targets are met. <b>Expeditions</b> share three account attempts per UTC day: Dust Tunnels costs 12 energy at level 1, Crystal Caves 18 at level 10, Guardian Rift 24 at level 25. Market offers rotate daily with one unit of personal stock each. Crafting spends the recipe’s listed materials for its output. Bag items are consumed when used. Check storage limits and quotes before confirming; free navigation and equipment switching award no shopping credit.</p><p>Moon Gold trades risk 10–250 Gold with a 5-minute account cooldown: inspect the possible loss as well as the possible reward.</p>' },
    { id: 'progression', title: 'Lifetime Progression And Competitions', body: '<p>Lifetime Pet XP, level, evolution, Care/Training/Adventure/Arena/Job/Bond specialist tracks, identity, memories, Marks and Crests stay with the earning pet. Specialist XP measures how it is played; it is separate from Pet XP. Account currencies and owned items are shared.</p><p>Daily and weekly Pet XP ranks measure awards in those periods; weekly competition resets Monday at 00:00 UTC. Seasonal ranks and <b>Account Season XP</b> use UTC calendar quarters (January–March, April–June, July–September, October–December). All-time ranks total lifetime Pet XP per player; Run Depth ranks the deepest authoritative room reached. Contract Rank is separate. Your pet continues through each boundary.</p><p>In PROFILE, claim account season tiers at <b>250, 1,000, 3,000 and 7,500 Account Season XP</b>: respectively 80 Gold + 1 Style; 160 Gold + 3 Crystals + 2 Style; 260 Gold + 6 Crystals + 4 Style; 420 Gold + 10 Crystals + 8 Style, plus the displayed evolution Style bonus. Claims pay once per account, tier and quarter; earlier unlocked unclaimed tiers remain recoverable.</p><p>Linked <b>Community XP</b> has its own main profile and competition season; Pet XP and specialist XP are not added to it. Pet rewards share account caps of <b>1,200 Pet XP and 250 Community XP per UTC day</b>. Other limits apply to specialist progress, items and materials. Capped rewards can be lower than previews, and repeatable play does not guarantee unlimited rewards.</p>' },
    { id: 'recovery', title: 'Saved Activities And Interrupted Rewards', body: '<p>Your progress is saved by the server. Reopen with the same Telegram account, choose the source pet in PROFILE and use the amber <b>Refresh</b> control after an interruption. Closing the app does not cancel an activity or abandon a saved run, Contract or Finale.</p><p>Follow <b>Play Now</b> or the original panel’s saved control: Recover Saved Reward for a timed claim; Finish Saved Daily Run; Retry Saved XP Bonus for a Contract; Recover Weekly Reward; Claim Saved Raid Reward; or Claim Finale Reward. Resume saved district/story/raid choices with their original choice; already paid energy is not charged again. Standard run endings and saved Arena/Kaiju results also reconcile through refresh and their battle/run panel.</p><p>Saved rewards keep the original pet and accounting window, even after a switch or calendar boundary. Retry completes that saved settlement once; it does not promise a new capped payout. If a read fails, retain the last valid view and refresh before another action. Resolve blocking sessions and pending rewards before switching or deleting a pet.</p>' },
    { id: 'audio', title: 'Canvas Controls, Dance And Inspire Bot', body: '<p>The cyan <b>Audio</b> speaker toggles game sound effects and the generated game score; the score pauses while Radio is requested. The purple <b>Radio</b> button plays/stops GraffPUNKS Radio independently; Loading means connecting and Retry means the stream failed. Audio mute does not mute Radio. Browsers can require a fresh tap before audio plays.</p><p><b>Dance</b> starts the station from your tap and runs its pose once playback connects. An accepted dance lasts about 3.6 seconds after connection, then stops the station; a replacement pose, failed action or leaving the app also ends its temporary playback. If the stream fails, Dance still animates and its saved care effect stands; there is no automatic extra care request. Tapping Radio takes manual control and can keep playback on after the pose. Dance is stat-only care, not incubation.</p><p><b>Inspire Bot</b> is the silent incubation option in the Secret Bot Chamber. It adds 2 inspiration signal and rhythm affinity to the egg’s saved incubation history. It never starts Radio or plays a song and cannot reveal the identity early. Warm, Talk and Rest record their own affinity signals. These choices influence the derived hatch identity and temperament; no button selects a guaranteed named character.</p>' }
  ];
  var about = [
    { id: 'about', title: 'About Moonpet OS', body: '<p>Moonpet OS is the Crypto Moonboys Telegram Mini App companion RPG. Adopt EGGYONE, raise a persistent Moonpet through care, missions, work, exploration and combat, and build its lifetime progression. @WIKICOMSBOT launches the signed app and delivers enabled alerts; the website hosts the public guide, wiki and leaderboards.</p>' },
    { id: 'ownership', title: 'A Persistent Companion', body: '<p><b>Pets persist: no automatic seasonal reset, replacement or retirement.</b> Your pet’s identity, needs, XP, specialist tracks, evolution, Marks, Crests and memories continue across UTC competition quarters. Purchased pet spaces also remain owned. Only a confirmed voluntary Delete archives a companion and starts a fresh egg in its owned space.</p>' },
    { id: 'identity', title: 'Hatching Is The Beginning', body: '<p>EGGYONE is the shared Secret Bot; hatching triggers its BREAKOUT animation and the shared WTFBOI presentation. The assigned identity stays <b>UNKNOWN</b> through Stages 0, 1 and 2. The canonical name appears at <b>Stage 3, Elite Moonpet</b>, after its level, age, Marks, Crests, boss, relic and material requirements are met. It takes at least 84 days of ownership; Legendary evolution takes at least 365 days. These are minimums, not automatic upgrades. Legendary completion needs final evolution, 240 distinct-day Growth Marks and 44 distinct-week Crests.</p>' },
    { id: 'play', title: 'Play And Progress', body: '<p>The current build includes Care, Daily Journey, Weekly Journey, seven daily missions, jobs, timed activities, Standard and Daily Moon Runs, Continuing Contracts, districts, stories, equipment, crafting, bounties, expeditions, Arena, Kaiju, bosses and Season Finale. Pet XP develops each pet; daily, weekly and quarterly ranks measure separate competition periods. Community XP is a separate linked profile score.</p><p>Moon Gold, Moon Crystals and Style Tokens fund game-only rewards and upgrades. Arcade XP is earned through website play and qualifies or buys pet spaces. There are no cash purchases, token cash-out or paid recovery routes. Read How to Play for exact entry, costs, cooldowns, claims and save recovery; each action’s live panel shows its requirements before you commit.</p>' }
  ];
  function website(items, className) {
    return items.map(function (s) {
      var body = s.body;
      if (className === 'wiki-section' && s.id === 'about') body = body.replace('<p>', '<p class="lead-paragraph">');
      if (className === 'wiki-section' && s.id === 'pets') {
        body = '<div class="pets-live-grid">' + body.replace(/<p>/g, '<article class="pets-live-card"><p>').replace(/<\/p>/g, '</p></article>') + '</div>';
      }
      return '<section class="' + className + '" id="moonpet-' + s.id + '"><h2>' + s.title + '</h2>' + body + '</section>';
    }).join('\n');
  }
  function game(items) {
    return items.map(function (s, index) {
      return '<details class="guide-step"' + (index < 2 ? ' open' : '') + '><summary>' + s.title + '</summary>' + s.body + '</details>';
    }).join('');
  }
  return { stages: stages, care: care, sections: sections, about: about, website: website, game: game };
});
