// Generated by CoffeeScript 1.7.1
// bkcore.ImageData — load an image and expose per-pixel colour data.
// Used by the track analyser for collision/checkpoint detection.
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});

  bkcore.ImageData = (function() {
    // url      — path to the image
    // callback — invoked once the pixel data is ready
    function ImageData(url, callback) {
      var self = this;
      this.loaded = false;
      this.pixels = null;
      this._data  = null;

      var img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = function() {
        var canvas = document.createElement('canvas');
        canvas.width  = img.width;
        canvas.height = img.height;
        var ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        var imageData = ctx.getImageData(0, 0, img.width, img.height);
        self.pixels = { width: img.width, height: img.height };
        self._data  = imageData.data;
        self.loaded = true;
        if (typeof callback === 'function') {
          callback(self);
        }
      };
      img.src = url;
    }

    // Returns {r, g, b, a} (0–255) for the pixel at (x, y).
    // Returns black with full alpha when coordinates are out of range or
    // pixel data has not loaded yet.
    ImageData.prototype.getPixel = function(x, y) {
      if (!this._data || !this.pixels) {
        return { r: 0, g: 0, b: 0, a: 255 };
      }
      x = Math.floor(x);
      y = Math.floor(y);
      if (x < 0 || y < 0 || x >= this.pixels.width || y >= this.pixels.height) {
        return { r: 0, g: 0, b: 0, a: 255 };
      }
      var i = (y * this.pixels.width + x) * 4;
      return {
        r: this._data[i],
        g: this._data[i + 1],
        b: this._data[i + 2],
        a: this._data[i + 3]
      };
    };

    // Returns {r, g, b, a} bilinearly interpolated at the sub-pixel position (x, y).
    // Used by ShipControls for smooth collision detection.
    ImageData.prototype.getPixelBilinear = function(x, y) {
      if (!this._data || !this.pixels) {
        return { r: 0, g: 0, b: 0, a: 255 };
      }
      var x0 = Math.floor(x), x1 = x0 + 1;
      var y0 = Math.floor(y), y1 = y0 + 1;
      var fx = x - x0, fy = y - y0;
      var p00 = this.getPixel(x0, y0);
      var p10 = this.getPixel(x1, y0);
      var p01 = this.getPixel(x0, y1);
      var p11 = this.getPixel(x1, y1);
      var w00 = (1 - fx) * (1 - fy);
      var w10 = fx * (1 - fy);
      var w01 = (1 - fx) * fy;
      var w11 = fx * fy;
      return {
        r: w00 * p00.r + w10 * p10.r + w01 * p01.r + w11 * p11.r,
        g: w00 * p00.g + w10 * p10.g + w01 * p01.g + w11 * p11.g,
        b: w00 * p00.b + w10 * p10.b + w01 * p01.b + w11 * p11.b,
        a: w00 * p00.a + w10 * p10.a + w01 * p01.a + w11 * p11.a
      };
    };

    // Returns a bilinearly interpolated value packed as r*65536 + g*256 + b.
    // NOTE: ShipControls.heightCheck now uses an inline _readHeight() helper
    // (g*256+b formula) suited to the Cityscape height.png encoding.
    // This method is preserved for compatibility with other callers.
    ImageData.prototype.getPixelFBilinear = function(x, y) {
      var p = this.getPixelBilinear(x, y);
      return p.r * 65536 + p.g * 256 + p.b;
    };

    return ImageData;

  })();

}).call(this);
