// Generated by CoffeeScript 1.7.1
// bkcore.ImageData — load an image and expose per-pixel colour data.
// Used by the track analyser for collision/checkpoint detection.
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});

  bkcore.ImageData = (function() {
    // url      — path to the image
    // callback — invoked once the pixel data is ready
    function ImageData(url, callback) {
      var self = this;
      this.pixels = null;
      this._data  = null;

      var img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = function() {
        var canvas = document.createElement('canvas');
        canvas.width  = img.width;
        canvas.height = img.height;
        var ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        var imageData = ctx.getImageData(0, 0, img.width, img.height);
        self.pixels = { width: img.width, height: img.height };
        self._data  = imageData.data;
        if (typeof callback === 'function') {
          callback(self);
        }
      };
      img.src = url;
    }

    // Returns {r, g, b, a} (0–255) for the pixel at (x, y).
    // Returns black with full alpha when coordinates are out of range or
    // pixel data has not loaded yet.
    ImageData.prototype.getPixel = function(x, y) {
      if (!this._data || !this.pixels) {
        return { r: 0, g: 0, b: 0, a: 255 };
      }
      x = Math.floor(x);
      y = Math.floor(y);
      if (x < 0 || y < 0 || x >= this.pixels.width || y >= this.pixels.height) {
        return { r: 0, g: 0, b: 0, a: 255 };
      }
      var i = (y * this.pixels.width + x) * 4;
      return {
        r: this._data[i],
        g: this._data[i + 1],
        b: this._data[i + 2],
        a: this._data[i + 3]
      };
    };

    return ImageData;

  })();

}).call(this);
