// Generated by CoffeeScript 1.7.1
// bkcore.Timer — high-resolution game timer
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});

  bkcore.Timer = (function() {
    function Timer() {
      this.time = {
        start: 0,
        elapsed: 0,
        delta: 0,
        previous: 0
      };
    }

    Timer.prototype.start = function() {
      var now;
      now = Date.now();
      this.time.start = now;
      this.time.previous = now;
      this.time.elapsed = 0;
      this.time.delta = 0;
    };

    Timer.prototype.update = function() {
      var now;
      now = Date.now();
      this.time.delta = now - this.time.previous;
      this.time.elapsed = now - this.time.start;
      this.time.previous = now;
    };

    Timer.prototype.getElapsedTime = function() {
      return this.time.elapsed;
    };

    Timer.msToTimeString = function(ms) {
      var m, s, mss;
      if (ms == null || isNaN(ms)) {
        return { m: '00', s: '00', ms: '000' };
      }
      m   = Math.floor(ms / 60000);
      s   = Math.floor((ms % 60000) / 1000);
      mss = Math.floor(ms % 1000);
      return {
        m:  m < 10 ? '0' + m   : '' + m,
        s:  s < 10 ? '0' + s   : '' + s,
        ms: mss < 10 ? '00' + mss : mss < 100 ? '0' + mss : '' + mss
      };
    };

    Timer.msToTime = function(ms) {
      return Timer.msToTimeString(ms);
    };

    return Timer;

  })();

}).call(this);
