// Generated by CoffeeScript 1.7.1
// bkcore.Utils — miscellaneous helpers used by HexGL
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});

  bkcore.Utils = (function() {
    function Utils() {}

    // Read a named parameter from the current URL query string.
    // Returns null when the parameter is absent.
    Utils.getURLParameter = function(name) {
      var match;
      match = new RegExp('[?&]' + encodeURIComponent(name) + '=([^&]*)').exec(window.location.search);
      if (match) {
        return decodeURIComponent(match[1]);
      }
      return null;
    };

    // Returns true when the browser exposes touch events (mobile / tablet).
    Utils.isTouchDevice = function() {
      return 'ontouchstart' in window || (navigator.maxTouchPoints != null && navigator.maxTouchPoints > 0);
    };

    // Build a THREE.MeshPhongMaterial with optional normal-map support.
    // opts:
    //   diffuse      — THREE.Texture
    //   specular     — THREE.Texture
    //   normal       — THREE.Texture
    //   normalScale  — number (default 1.0)
    //   cube         — THREE.CubeTexture (env map)
    //   reflectivity — number
    //   ambient      — hex colour
    //   shininess    — number
    //   metal        — bool
    //   perPixel     — bool
    Utils.createNormalMaterial = function(opts) {
      var params;
      params = {
        map:        opts.diffuse   || null,
        specularMap: opts.specular || null,
        normalMap:  opts.normal    || null,
        ambient:    new THREE.Color(opts.ambient != null ? opts.ambient : 0x000000),
        shininess:  opts.shininess != null ? opts.shininess : 30,
        metal:      opts.metal     || false
      };
      if (opts.normalScale != null) {
        params.normalScale = new THREE.Vector2(opts.normalScale, opts.normalScale);
      }
      if (opts.cube != null) {
        params.envMap = opts.cube;
        params.reflectivity = opts.reflectivity != null ? opts.reflectivity : 1.0;
      }
      return new THREE.MeshPhongMaterial(params);
    };

    // Minimal synchronous-capable XHR wrapper.
    // callback(req) is invoked with the XMLHttpRequest on load.
    Utils.request = function(url, async, callback) {
      var req;
      req = new XMLHttpRequest();
      req.open('GET', url, async !== false);
      req.onload = function() {
        if (typeof callback === 'function') {
          callback(req);
        }
      };
      req.send(null);
    };

    return Utils;

  })();

}).call(this);
