// Generated by CoffeeScript 1.7.1
// bkcore.controllers.GamepadController — Gamepad API wrapper
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});
  bkcore.controllers = bkcore.controllers || {};

  bkcore.controllers.GamepadController = (function() {
    // Returns true when the browser supports the Gamepad API.
    GamepadController.isCompatible = function() {
      return typeof navigator.getGamepads === 'function' || typeof navigator.webkitGetGamepads === 'function';
    };

    // updateCallback — function(controllerState) called each time poll() is
    //                  invoked and a gamepad is connected.
    //                  controllerState: { lstickx, lsticky, acceleration,
    //                                     ltrigger, rtrigger, select }
    function GamepadController(updateCallback) {
      this._callback    = updateCallback || null;
      this._available   = false;

      // Public axes/button values — read directly by ShipControls.
      this.lstickx      = 0;
      this.lsticky      = 0;
      this.acceleration = 0;
      this.ltrigger     = 0;
      this.rtrigger     = 0;
      this.select       = false;

      // Poll the Gamepad API on every animation frame.
      var self = this;
      function poll() {
        self._poll();
        requestAnimationFrame(poll);
      }
      requestAnimationFrame(poll);
    }

    // Returns true if a gamepad update was available on the last poll.
    GamepadController.prototype.updateAvailable = function() {
      return this._available;
    };

    GamepadController.prototype._poll = function() {
      var gamepads, gp, i;
      gamepads = navigator.getGamepads
        ? navigator.getGamepads()
        : (navigator.webkitGetGamepads ? navigator.webkitGetGamepads() : []);

      gp = null;
      for (i = 0; i < gamepads.length; i++) {
        if (gamepads[i] && gamepads[i].connected) {
          gp = gamepads[i];
          break;
        }
      }

      if (!gp) {
        this._available = false;
        return;
      }

      this._available   = true;
      this.lstickx      = gp.axes[0] || 0;
      this.lsticky      = gp.axes[1] || 0;
      // Right trigger (R2/RT, index 7) → forward acceleration
      this.acceleration = gp.buttons[7] ? gp.buttons[7].value : 0;
      // Left trigger (L2/LT, index 6) → left air-brake
      this.ltrigger     = gp.buttons[6] ? gp.buttons[6].value : 0;
      // Right bumper (R1/RB, index 5) → right air-brake
      this.rtrigger     = gp.buttons[5] ? gp.buttons[5].value : 0;
      // Select / back button (index 8 or 9)
      this.select       = !!(gp.buttons[8] && gp.buttons[8].pressed) || !!(gp.buttons[9] && gp.buttons[9].pressed);

      if (typeof this._callback === 'function') {
        this._callback({
          lstickx:      this.lstickx,
          lsticky:      this.lsticky,
          acceleration: this.acceleration,
          ltrigger:     this.ltrigger,
          rtrigger:     this.rtrigger,
          select:       this.select
        });
      }
    };

    return GamepadController;

  })();

}).call(this);
