// Generated by CoffeeScript 1.7.1
// bkcore.controllers.OrientationController — device-tilt steering
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});
  bkcore.controllers = bkcore.controllers || {};

  bkcore.controllers.OrientationController = (function() {
    // Returns true when the browser exposes DeviceOrientationEvent.
    OrientationController.isCompatible = function() {
      return typeof DeviceOrientationEvent !== 'undefined';
    };

    // domElement        — element that receives fallback touch events
    // useTouchFallback  — if true, also attach touch events for thrust control
    // touchCallback     — function(state, touch, event) called on touch events
    function OrientationController(domElement, useTouchFallback, touchCallback) {
      var self = this;

      // beta is the front-to-back tilt in degrees (−180 … 180).
      // ShipControls reads it as: beta/45 * angularSpeed * dt
      this.beta  = 0;
      this.gamma = 0;
      this.alpha = 0;

      function onDeviceOrientation(event) {
        // beta:  front/back tilt  (we use for left/right steering here to
        //        match the original HexGL behaviour where the phone is held
        //        in landscape mode and tilted sideways)
        self.beta  = event.gamma != null ? event.gamma : 0;
        self.gamma = event.beta  != null ? event.beta  : 0;
        self.alpha = event.alpha != null ? event.alpha : 0;
      }

      window.addEventListener('deviceorientation', onDeviceOrientation, false);

      if (useTouchFallback && domElement) {
        function onTouchStart(event) {
          if (typeof touchCallback === 'function') {
            touchCallback({ beta: self.beta }, event.changedTouches[0], event);
          }
        }
        function onTouchEnd(event) {
          if (typeof touchCallback === 'function') {
            touchCallback({ beta: self.beta }, event.changedTouches[0], event);
          }
        }
        domElement.addEventListener('touchstart',  onTouchStart, false);
        domElement.addEventListener('touchend',    onTouchEnd,   false);
        domElement.addEventListener('touchcancel', onTouchEnd,   false);
      }
    }

    return OrientationController;

  })();

}).call(this);
