// Generated by CoffeeScript 1.7.1
// bkcore.controllers.TouchController — virtual joystick for touch devices
(function() {
  var bkcore;

  bkcore = this.bkcore || (this.bkcore = {});
  bkcore.controllers = bkcore.controllers || {};

  bkcore.controllers.TouchController = (function() {
    // Returns true when the browser supports touch events.
    TouchController.isCompatible = function() {
      return 'ontouchstart' in window || (navigator.maxTouchPoints != null && navigator.maxTouchPoints > 0);
    };

    // domElement    — element that receives touch events
    // halfWidth     — horizontal midpoint of the play area (pixels)
    // touchCallback — function(state, touch, event) called on every touch event
    function TouchController(domElement, halfWidth, touchCallback) {
      var self = this;

      // Virtual stick position; x is in arbitrary units scaled by callers.
      this.stickVector = { x: 0, y: 0 };
      this._halfWidth   = halfWidth || (window.innerWidth / 2);
      this._active      = false;
      this._origin      = { x: 0, y: 0 };

      function onTouchStart(event) {
        event.preventDefault();
        var touch = event.changedTouches[0];
        self._active   = true;
        self._origin.x = touch.clientX;
        self._origin.y = touch.clientY;
        self.stickVector.x = 0;
        self.stickVector.y = 0;
        if (typeof touchCallback === 'function') {
          touchCallback({ active: self._active, stickVector: self.stickVector }, touch, event);
        }
      }

      function onTouchMove(event) {
        event.preventDefault();
        if (!self._active) return;
        var touch = event.changedTouches[0];
        self.stickVector.x = (touch.clientX - self._origin.x);
        self.stickVector.y = (touch.clientY - self._origin.y);
        if (typeof touchCallback === 'function') {
          touchCallback({ active: self._active, stickVector: self.stickVector }, touch, event);
        }
      }

      function onTouchEnd(event) {
        event.preventDefault();
        self._active       = false;
        self.stickVector.x = 0;
        self.stickVector.y = 0;
        var touch = event.changedTouches[0];
        if (typeof touchCallback === 'function') {
          touchCallback({ active: self._active, stickVector: self.stickVector }, touch, event);
        }
      }

      domElement.addEventListener('touchstart',  onTouchStart, false);
      domElement.addEventListener('touchmove',   onTouchMove,  false);
      domElement.addEventListener('touchend',    onTouchEnd,   false);
      domElement.addEventListener('touchcancel', onTouchEnd,   false);
    }

    return TouchController;

  })();

}).call(this);
