import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

const seasonCompletion = read('workers/moonboys-api/pets/season-completion.js');
const seasonAuthority = read('workers/moonboys-api/pets/season-authority.js');
const dailyMoonRun = read('workers/moonboys-api/pets/daily-moon-run.js');
const weeklyJourney = read('workers/moonboys-api/pets/weekly-journey.js');
const rogueliteFoundation = read('workers/moonboys-api/pets/roguelite-foundation.js');
const runtimePhase5a = read('workers/moonboys-api/pets/runtime-phase-5a.js');
const liveSystems = read('workers/moonboys-api/pets/live-systems.js');
const specialistMigration = read('workers/moonboys-api/migrations/073_moonpet_per_pet_specialist_progression.sql');
const breedingAuthority = read('workers/moonboys-api/pets/breeding-authority.js');
const sanctuary = read('workers/moonboys-api/pets/sanctuary.js');
const worker = read('workers/moonboys-api/worker.js');
const rewardAuthorityRegression = read('scripts/moonpet-reward-pet-id-authority.test.mjs');
const identityIsolationRegression = read('scripts/telegram-pets-identity-expansion.test.mjs');

assert.match(seasonCompletion, /required_growth_marks:\s*60/, 'Season completion must keep the 60 Growth Mark target.');
assert.match(seasonCompletion, /required_weekly_crests:\s*10/, 'Season completion must keep the 10 Weekly Crest target.');
assert.match(seasonCompletion, /season_days:\s*90/, 'Season completion must keep the 90-day Season 1 target.');
assert.match(seasonAuthority, /Math\.floor\(date\.getUTCMonth\(\) \/ 3\)/,
  'Moonpet season keys must stay on the shared quarter authority.');
assert.doesNotMatch(`${seasonAuthority}\n${dailyMoonRun}\n${rogueliteFoundation}`, /dayOfYear|Math\.floor\(dayOfYear \/ 90\)/,
  'Runtime season authority must not reintroduce an independent day-of-year season key.');

assert.match(seasonCompletion, /WHERE s\.pet_id=\? AND s\.season_key=\?\$\{ownerClause\}/,
  'Growth and Crest awards must resolve an owned pet in the requested season.');
assert.match(seasonCompletion, /currentEvolutionProgress\.complete[\s\S]*levelProgress\.complete[\s\S]*ageProgress\.complete[\s\S]*growthMarkProgress\.complete[\s\S]*weeklyCrestProgress\.complete/,
  'Evolution readiness must require current stage, level, age, Growth Marks, and Weekly Crests together.');
assert.match(seasonCompletion, /WHERE pet_id=\? AND telegram_id=\? AND season_key=\? AND earned_day=\?/,
  'Growth Mark duplicate checks must stay pet, owner, season, and day scoped.');
assert.match(seasonCompletion, /crest:\$\{petId\}:\$\{seasonKey\}:\$\{week\}:\$\{objective\.objective_id\}/,
  'Weekly Crest ids must stay pet, season, week, and objective scoped.');

assert.match(dailyMoonRun, /INSERT OR IGNORE INTO telegram_pet_daily_journey_objectives[\s\S]*telegramId, petId, seasonId, utcDay/,
  'Daily Journey objective evidence must persist with pet_id, season, and UTC day.');
assert.match(dailyMoonRun, /evidenceKey = `daily-run:\$\{request\.utc_day\}:\$\{DAILY_JOURNEY_REQUIRED_OBJECTIVES\}-of-\$\{DAILY_JOURNEY_TOTAL_OBJECTIVES\}`/,
  'Daily Journey Growth Mark evidence must be generated by the runtime qualification path.');
assert.match(dailyMoonRun, /reason: 'daily_journey_growth_mark_duplicate'/,
  'Daily Journey duplicate settlement must remain explicit and non-awarding.');

assert.match(weeklyJourney, /WEEKLY_JOURNEY_REQUIRED_OBJECTIVES !== WEEKLY_JOURNEY_TOTAL_OBJECTIVES/,
  'Weekly Journey Crest qualification must stay full-completion gated.');
assert.match(weeklyJourney, /String\(sourceEvent\.season_key \|\| ''\) !== seasonKey/,
  'Weekly Journey evidence must reject source events from the wrong season.');
assert.match(weeklyJourney, /String\(sourceEvent\.pet_id \|\| ''\) !== petId/,
  'Weekly Journey evidence must reject source events from the wrong pet.');
assert.match(weeklyJourney, /dayBelongsToQualificationWeek\(day, season, qualificationWeek\)/,
  'Weekly Journey evidence must stay bounded to the claimed qualification week.');
assert.match(weeklyJourney, /awardPetWeeklyCrest\(db, \{[\s\S]*objective: 'weekly_journey'/,
  'Weekly Journey Crest minting must go through the shared Crest authority helper.');

assert.match(rogueliteFoundation, /const petOwnerGuard = petAuthority[\s\S]*EXISTS \(SELECT 1 FROM telegram_pet_instances WHERE pet_id = \? AND telegram_id = \? AND season_key = \?\)/,
  'Reward settlement must prove the requested pet_id belongs to the Telegram owner and season.');
assert.match(rogueliteFoundation, /\$\{petOwnerGuard\}\s+\$\{authorization\.sql\}\s+\$\{reservationGuard\}/,
  'Reward settlement SQL must inject the pet ownership guard into the claim reservation query.');
assert.match(rogueliteFoundation, /source = \? AND idempotency_key = \?/,
  'Reward settlement retries must use the private source/idempotency ledger.');
assert.match(rogueliteFoundation, /moon_gold:\s*Math\.min\(rewards\.moon_gold,\s*MAX_ROGUELITE_MOON_GOLD_PER_CLAIM\)/,
  'Roguelite Moon Gold rewards must be clamped in the settlement path.');
assert.match(rogueliteFoundation, /moon_crystals:\s*Math\.min\(rewards\.moon_crystals,\s*MAX_ROGUELITE_MOON_CRYSTALS_PER_CLAIM\)/,
  'Roguelite Moon Crystal rewards must be clamped in the settlement path.');
assert.match(rogueliteFoundation, /style_tokens:\s*Math\.min\(rewards\.style_tokens,\s*MAX_ROGUELITE_STYLE_TOKENS_PER_CLAIM\)/,
  'Roguelite Style rewards must be clamped in the settlement path.');
assert.match(rogueliteFoundation, /requestedPetId && \(existingPetId !== petId \|\| existingSeasonKey !== seasonKey\)/,
  'Existing runs must reject stale pet or season authority reuse.');
assert.match(specialistMigration, /PRIMARY KEY \(pet_id, telegram_id, season_key\)/,
  'Specialist progression must remain isolated to the pet ownership tuple.');
assert.match(specialistMigration, /UNIQUE \(pet_id, telegram_id, season_key, event_key\)/,
  'Specialist progression events must stay idempotent per pet ownership tuple.');
assert.match(runtimePhase5a, /SELECT \* FROM telegram_pet_specialist_progression WHERE pet_id = \? AND telegram_id = \? AND season_key = \?/,
  'Specialist progression reads must stay scoped to the selected pet ownership tuple.');
assert.match(rewardAuthorityRegression, /switching active pets cannot redirect Pet XP or hide the account-owned wallet/,
  'Live reward ownership must remain pinned to the source pet after active-pet switches.');
assert.match(identityIsolationRegression, /Pet A receives personality authority after active pet switch/,
  'Identity/personality ownership must remain on the source pet after active-pet switches.');
assert.match(identityIsolationRegression, /Pet A receives achievement authority after active pet switch/,
  'Achievement ownership must remain on the source pet after active-pet switches.');
assert.match(identityIsolationRegression, /Pet A receives boss victory authority after active pet switch/,
  'Boss history ownership must remain on the source pet after active-pet switches.');
assert.match(rogueliteFoundation, /source === 'pet_district' \|\| source === 'pet_event_chain'/,
  'District and event-chain rewards must keep explicit pet-owned source checks.');
assert.match(rogueliteFoundation, /telegram_pet_system_events WHERE id = \? AND telegram_id = \? AND pet_id = \? AND season_key = \?/,
  'District and event-chain rewards must verify the stored pet ownership tuple.');
assert.match(rogueliteFoundation, /source === 'pet_seasonal_boss'/,
  'Seasonal boss reward settlement must keep explicit pet-owned source checks.');
assert.match(rogueliteFoundation, /telegram_pet_seasonal_boss_progress WHERE pet_id = \? AND telegram_id = \? AND pet_season_key = \? AND season_key = \? AND boss_key = \? AND defeated_at IS NOT NULL/,
  'Seasonal boss rewards must verify pet/owner/season authority on boss progress rows.');
assert.match(liveSystems, /INSERT OR IGNORE INTO telegram_pet_system_events[\s\S]*authority\.pet_id, telegramId, authority\.season_key/,
  'Live-system event reservations must persist pet-owned authority tuples.');

assert.match(breedingAuthority, /JOIN telegram_pet_season_completions c[\s\S]*WHERE i\.pet_id=\? AND i\.telegram_id=\? AND i\.season_key=\?/,
  'Future parent systems must remain locked behind completed pets in the same season.');
assert.match(breedingAuthority, /breeding_season_authority_mismatch/,
  'Future parent systems must reject stale season authority.');
assert.match(sanctuary, /isSeasonSettlementReconciliation/,
  'Sanctuary movement must remain behind explicit season settlement reconciliation.');
assert.match(sanctuary, /const explicitSettlement = isSeasonSettlementReconciliation\(options\);[\s\S]*const seasonFilter = explicitSettlement \? '' : ' AND c\.season_key<>\?';/,
  'Completed-pet reconciliation must use the explicit settlement helper to decide current-season filtering.');
assert.match(sanctuary, /transitions\.push\(await movePetToSanctuaryIfEligible\(db, completion, options\)\);/,
  'Completed-pet reconciliation must route eligible pets through the Sanctuary movement authority.');
assert.doesNotMatch(seasonCompletion, /movePetToSanctuaryIfEligible/,
  'Adult/season completion must not immediately move active pets into later systems.');

assert.match(worker, /if \(result\.accepted && !result\.duplicate\) result\.lifecycle = await syncMoonpetLifecycleStage\(db, telegramId, next\.stage\);/,
  'API evolution handling must sync lifecycle only after a newly accepted unlock.');

console.log('moonpet-runtime-audit-completion.test.mjs passed');
