import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import { listSanctuaryPets, movePetToSanctuaryIfEligible } from '../workers/moonboys-api/pets/sanctuary.js';
class Statement { constructor(db, sql, args=[]) { this.db=db; this.sql=sql; this.args=args; } bind(...args){return new Statement(this.db,this.sql,args)} async first(){return this.db.prepare(this.sql).get(...this.args)||null} async all(){return {results:this.db.prepare(this.sql).all(...this.args)}} async run(){const r=this.db.prepare(this.sql).run(...this.args);return {meta:{changes:r.changes}}} }
class D1 { constructor(db){this.db=db} prepare(sql){return new Statement(this.db,sql)} }
const sqlite=new DatabaseSync(':memory:');
sqlite.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE telegram_pet_profiles(telegram_id TEXT PRIMARY KEY);
CREATE TABLE telegram_pet_season_slots(pet_id TEXT PRIMARY KEY,telegram_id TEXT,season_key TEXT,slot_number INTEGER,status TEXT,updated_at TEXT);
CREATE TABLE telegram_pet_instances(pet_id TEXT PRIMARY KEY,telegram_id TEXT,season_key TEXT,pet_name TEXT,species TEXT,stage TEXT,equipped_food TEXT,equipped_toy TEXT,equipped_outfit TEXT,equipped_armor TEXT,equipped_weapon TEXT,equipped_charm TEXT,status TEXT,updated_at TEXT);
CREATE TABLE telegram_pet_active_slots(telegram_id TEXT PRIMARY KEY,pet_id TEXT,season_key TEXT);
CREATE TABLE telegram_pet_season_completions(pet_id TEXT,telegram_id TEXT,season_key TEXT,completed_at TEXT,legendary_evolution_id TEXT,PRIMARY KEY(pet_id,season_key));
CREATE TABLE telegram_pet_lifecycle_by_pet(pet_id TEXT PRIMARY KEY,telegram_id TEXT,species_id TEXT,palette_id TEXT,rare_morph_id TEXT);
CREATE TABLE telegram_pet_evolutions_by_pet(pet_id TEXT,telegram_id TEXT,evolution_id TEXT,stage INTEGER,cosmetic_unlocks TEXT,achievement_unlocks TEXT,unlocked_at TEXT);
CREATE TABLE telegram_pet_personality_traits(telegram_id TEXT,trait_id TEXT,progress INTEGER,unlocked_at TEXT);
CREATE TABLE telegram_pet_memories(telegram_id TEXT PRIMARY KEY,milestones TEXT,updated_at TEXT);
CREATE TABLE telegram_pet_inventory(telegram_id TEXT,asset_type TEXT,asset_key TEXT,quantity INTEGER);
CREATE TABLE telegram_pet_equipment_progression(telegram_id TEXT,item_key TEXT,slot TEXT,item_level INTEGER,mastery_tier INTEGER);
CREATE TABLE telegram_pet_progression(telegram_id TEXT PRIMARY KEY,traits_json TEXT);
INSERT INTO telegram_pet_profiles VALUES('owner'),('attacker');
INSERT INTO telegram_pet_season_slots VALUES('complete','owner','s1',1,'active',NULL),('legendary-only','owner','s1',2,'active',NULL);
INSERT INTO telegram_pet_instances VALUES('complete','owner','s1','Nova','legacy','legendary',NULL,NULL,'crown',NULL,'laser',NULL,'active',NULL),('legendary-only','owner','s1','Other','legacy','legendary',NULL,NULL,NULL,NULL,NULL,NULL,'active',NULL);
INSERT INTO telegram_pet_active_slots VALUES('owner','complete','s1');
INSERT INTO telegram_pet_season_completions VALUES('complete','owner','s1','2026-03-31T00:00:00Z','legendary_moon_guardian');
INSERT INTO telegram_pet_lifecycle_by_pet VALUES('complete','owner','lunar_fox','neon','neon_fox');
INSERT INTO telegram_pet_evolutions_by_pet VALUES('complete','owner','moon_egg',0,'[]','[]','2026-01-01'),('complete','owner','legendary_moon_guardian',4,'["crown"]','[]','2026-03-31');
INSERT INTO telegram_pet_personality_traits VALUES('owner','brave',100,'2026-02-01');
INSERT INTO telegram_pet_memories VALUES('owner','["first_boss"]',NULL);
INSERT INTO telegram_pet_inventory VALUES('owner','cosmetic','crown',1);
INSERT INTO telegram_pet_equipment_progression VALUES('owner','laser','weapon',5,2);
INSERT INTO telegram_pet_progression VALUES('owner','{"brave":100}');`);
sqlite.exec(await readFile(new URL('../workers/moonboys-api/migrations/059_telegram_pet_sanctuary.sql',import.meta.url),'utf8'));
const db=new D1(sqlite); const input={pet_id:'complete',telegram_id:'owner',season_key:'s1'};
assert.equal((await movePetToSanctuaryIfEligible(db,{...input,telegram_id:'attacker'})).reason,'pet_not_owned','ownership is authoritative');
assert.equal((await movePetToSanctuaryIfEligible(db,{pet_id:'legendary-only',telegram_id:'owner',season_key:'s1'})).reason,'season_not_complete','Legendary alone is rejected');
assert.equal((await movePetToSanctuaryIfEligible(db,input,{getPendingActivity:async()=>({run_id:'run'}),now:'2026-04-01T00:00:00Z'})).reason,'pending_activity');
assert.equal((await movePetToSanctuaryIfEligible(db,input,{getPendingActivity:async()=>null,now:'2026-04-01T00:00:00Z'})).accepted,true);
assert.equal(sqlite.prepare(`SELECT status FROM telegram_pet_instances WHERE pet_id='complete'`).get().status,'archived','resident cannot remain an active seasonal pet');
assert.equal(sqlite.prepare(`SELECT COUNT(*) count FROM telegram_pet_active_slots WHERE pet_id='complete'`).get().count,0);
const before=(await listSanctuaryPets(db,'owner'))[0]; assert.equal(before.cosmetics.equipment.equipped_outfit,'crown');
sqlite.prepare(`UPDATE telegram_pet_instances SET equipped_outfit='changed' WHERE pet_id='complete'`).run();
assert.equal((await listSanctuaryPets(db,'owner'))[0].cosmetics.equipment.equipped_outfit,'crown','snapshot is immutable when live state changes');
assert.equal((await movePetToSanctuaryIfEligible(db,input)).duplicate,true,'replay is idempotent');
assert.equal(sqlite.prepare('SELECT COUNT(*) count FROM telegram_pet_sanctuary').get().count,1,'unique pet permits one resident only');
assert.throws(() => sqlite.prepare(`UPDATE telegram_pet_sanctuary SET identity_snapshot_json='{}'`).run(), /sanctuary_snapshot_is_immutable/, 'historical snapshot columns are append-only');
assert.throws(() => sqlite.prepare(`DELETE FROM telegram_pet_sanctuary`).run(), /sanctuary_history_is_append_only/, 'Sanctuary history cannot be deleted');
console.log('telegram pets sanctuary tests passed');
